name: opencoodx
channels:
  - defaults
  - pytorch
dependencies:
  - pip==21.1.2
  - python==3.7.11
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pip:
    - matplotlib==3.4.2
    - numpy
    - open3d
    - opencv-python==4.5.5.62
    - cython
    - pygame
    - tensorboardX
    - shapely
    - einops
